spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mini-project
    username: postgres
    password: 123


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:1111/auth/realms/mann
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 100KB
  mail:
    host: smtp.gmail.com
    port: 587
    username: ruosraksa417@gmail.com
    password: sgxsicolnefhwlqb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true







#hibernate:
#  jdbc:
logging:
  level:
    com.levi.testhibernate: debug
#    batch_size: 1
storeFile : "http://localhost:8080/images/"
server:
  port: 8888












