spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

#hibernate:
#  jdbc:
logging:
  level:
    com.levi.testhibernate: debug
#    batch_size: 1